version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/payd.db:/app/payd.db
    environment:
      - GIN_MODE=release
    networks:
      - payd-net

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - payd-net

networks:
  payd-net:
    driver: bridge